services:
  django_og:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_og
    # command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8001:8000"
    depends_on:
      - db_og

  bot_og:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_og
    command: python manage.py app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - db_og

  db_og:
    image: postgres:15-alpine
    container_name: db_og
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
  
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django_og


volumes:
  postgres_data:
  static_volume:
  media_volume: